export const BASE_URL = "https://anidey.fun";
export const KOFI_URL = "https://ko-fi.com/anidey";

export const BANNERS = [
  {
    url: "/CSM.png",
    name: "Chainsaw Man",
    alt: "Chainsaw Man",
    title: "Chainsaw Man",
    genres: ["Action", "Drama"],
    rating: 84,
    description: `Denji is a teenage boy living with a Chainsaw Devil named Pochita. Due to the debt his father left behind, he has been living a rock-bottom life while repaying his debt by harvesting devil corpses with Pochita.One day, Denji is betrayed and killed. As his consciousness fades, he makes a contract with Pochita and gets revived as "Chainsaw Man" — a man with a devil's heart.`,
    status: "FINISHED",
    date: 2022,
    link: `watch/chainsaw-man-17406/127230/chainsaw-man-17406?ep=94597`,
  },
  {
    url: "/JJK_1.png",
    name: "Jujustu Kaisen",
    alt: "Jujustu Kaisen",
    title: "Jujustu Kaisen",
    genres: ["Action", "Drama"],
    rating: 85,
    description: `Yuji Itadori is a high school student with exceptional physical abilities. On the night his grandfather dies, his world changes forever when he encounters a cursed object. He swallows the finger of Sukuna, taking the curse into his own soul. From then on, he shares one body with Sukuna, the King of Curses.`,
    status: "FINISHED",
    date: 2021,
    link: `watch/jujutsu-kaisen-tv-534/113415/jujutsu-kaisen-tv-534?ep=10789`,
  },
  {
    url: "/OP.png",
    name: "One Piece",
    alt: "One Piece",
    title: "One Piece",
    genres: ["Action", "Adventure"],
    rating: 88,
    description: `Gol D. Roger was known as the "Pirate King," the strongest and most infamous being to have sailed the Grand Line. The capture and execution of Roger by the World Government brought a change throughout the world. His last words before his death revealed the existence of the greatest treasure in the world, One Piece. It was this revelation that brought about the Grand Age of Pirates`,
    status: "ONGOING",
    date: 1999,
    link: `watch/one-piece-100/21/one-piece-100?ep=2142`,
  },
  {
    url: "/YLIA.png",
    name: "Your Lie in April",
    alt: "Your Lie in April",
    title: "Your Lie in April",
    genres: ["Drama", "Music"],
    rating: 84,
    description: `Piano prodigy Arima Kousei dominated the competition and all child musicians knew his name. But after his mother, who was also his instructor, passed away, he had a mental breakdown while performing at a recital. This resulted in him no longer being able to hear the sound of his piano playing. Two years later, Kousei hasn’t touched the piano and views the world without any flair or color.`,
    status: "FINISHED",
    date: 2014,
    link: `watch/shigatsu-wa-kimi-no-uso-moments-946/20665/shigatsu-wa-kimi-no-uso-moments-946?ep=94660`,
  },
  {
    url: "/SAEKANO.png",
    name: "Saekano",
    alt: "Saekano",
    title: "Saekano: How to Raise a Boring Girlfriend",
    genres: ["Comedy", "Romance"],
    rating: 73,
    description: ` The life of Tomoyo Aki, a highschool otaku working part time to support his BD hoarding. With remarkable luck, he bumps head-first into Megumi Kato, the most beautiful girl he has ever seen. Naturally, the meeting twists his life into a complicated torrent of relationships. Eriri Spencer Sawamura, his half-foreigner childhood friend who’s always valued her relationship with MC.`,
    status: "FINISHED",
    date: 2015,
    link: `watch/saekano-how-to-raise-a-boring-girlfriend-1415/20657/saekano-how-to-raise-a-boring-girlfriend-1415?ep=20124`,
  },
];
