import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/toaster";
import { RecoilRoot } from "recoil";
import RecoilContextProvider from "../lib/recoil-context-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <RecoilContextProvider>
          <body className={`${inter.className} dark`}>
            <div className="absolute top-0 z-50 w-full">
              <Header />
            </div>
            {children}
            <Toaster />
          </body>
        </RecoilContextProvider>
      </SessionProvider>
    </html>
  );
}
